/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.oshente;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import oshi.SystemInfo;
import oshi.hardware.HardwareAbstractionLayer;

/**
 *
 * @author pedro
 */
public class Taskun extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Taskun() {
        initComponents();
        SystemInfo si = new SystemInfo();
        HardwareAbstractionLayer hal = si.getHardware();
        
        CPU cpu = new CPU();
        RAM ram = new RAM();
        HD hd = new HD();
        lblTempoAtividade.setText(cpu.getUptime());
        lblCPUDesempenho.setText(cpu.getDesempenho());
        lblRAMDesempenho.setText(ram.getDesempenhoMemoria());
        lblHDOcupado.setText(hd.getPorcentagemOcupada());
        lblThreands.setText(cpu.getThreads());
        lblProcesses.setText(cpu.getProcesses());
        
        lblDiscoRigido.setText(hd.getDiscoAlocado().replaceAll(" Fixo", ""));
        Integer valueDisk = Integer.parseInt(hd.getPorcentagemOcupada().replaceAll("%", ""));
        prgDisco.setValue(valueDisk);
        lblDiscoStatus.setText(hd.getDiscosTotalLivre());
        
        
        //Sistema Operacional
        lblSistema.setText(si.getOperatingSystem().toString());
        lblSistemBit.setText(String.format(" Sistema operacional de %d bits", (si.getOperatingSystem().getBitness())));
       
        //CPU
        lblCPUName.setText(cpu.getProcessador());
        
        //RAM
        lblRAMTotal.setText(ram.getTotalMemoria());
        lblRAMUtilizavel.setText(ram.getUtilizavel());
        lblRAMDisponivel.setText(ram.getDisponivel());
        lblRAMTipo.setText(ram.getTipoMemoria());
        lblRAMClock.setText(ram.getClockSpeed());
        
        //HD
        lblDisco.setText(hd.getDiscoAlocado().replaceAll(" Fixo", ""));
        lblDiscoTipo.setText(hd.getTipoSADisco());
        
        ActionListener action = (ActionEvent actionEvent) -> {
            
        
            System.out.println("Processando...");
            lblTempoAtividade.setText(cpu.getUptime());
            lblCPUDesempenho.setText(cpu.getDesempenho());
            lblRAMDesempenho.setText(ram.getDesempenhoMemoria());
            lblHDOcupado.setText(hd.getPorcentagemOcupada());
            lblThreands.setText(cpu.getThreads());
            lblProcesses.setText(cpu.getProcesses());
        
        };
        
        Timer timer = new Timer(10, action);
        timer.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRAMTotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblSistema = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblRAMUtilizavel = new javax.swing.JLabel();
        lblCPUName = new javax.swing.JLabel();
        lblRAMTipo = new javax.swing.JLabel();
        lblDiscoTipo = new javax.swing.JLabel();
        lblSistemBit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRAMDisponivel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRAMClock = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblCPUDesempenho = new javax.swing.JLabel();
        lblRAMDesempenho = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTempoAtividade = new javax.swing.JLabel();
        lblDiscoRigido = new javax.swing.JLabel();
        lblThreands = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblProcesses = new javax.swing.JLabel();
        prgDisco = new javax.swing.JProgressBar();
        lblHDOcupado = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblT1 = new javax.swing.JLabel();
        lblDiscoStatus = new javax.swing.JLabel();

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 204));

        jPanel1.setBackground(new java.awt.Color(27, 23, 49));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");

        lblDisco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblDisco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDisco.setText("_________");
        lblDisco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDisco.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(228, 87, 12));
        jLabel7.setText("RAM __________________________________________________________");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Memória:");

        lblRAMTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblRAMTotal.setText("___________");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Utilizável:");

        lblSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblSistema.setText("____________________________");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(228, 87, 12));
        jLabel9.setText("Disco Rígido_____________________________________________________");

        lblRAMUtilizavel.setForeground(new java.awt.Color(255, 255, 255));
        lblRAMUtilizavel.setText("___________");

        lblCPUName.setForeground(new java.awt.Color(255, 255, 255));
        lblCPUName.setText("________________________________________");

        lblRAMTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblRAMTipo.setText("__________");

        lblDiscoTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscoTipo.setText("_____");

        lblSistemBit.setForeground(new java.awt.Color(255, 255, 255));
        lblSistemBit.setText("_____");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema Operacional:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Disponível: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(228, 87, 12));
        jLabel2.setText("Sistema _______________________________________________________");

        lblRAMDisponivel.setForeground(new java.awt.Color(255, 255, 255));
        lblRAMDisponivel.setText("__________");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de sistema:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Velocidade:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(228, 87, 12));
        jLabel4.setText("Processador ____________________________________________________");

        lblRAMClock.setForeground(new java.awt.Color(255, 255, 255));
        lblRAMClock.setText("__________");

        jSeparator1.setBackground(new java.awt.Color(228, 87, 12));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setBackground(new java.awt.Color(228, 87, 12));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(228, 87, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CPU");

        lblCPUDesempenho.setBackground(new java.awt.Color(228, 87, 12));
        lblCPUDesempenho.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblCPUDesempenho.setForeground(new java.awt.Color(228, 87, 12));
        lblCPUDesempenho.setText("10%");

        lblRAMDesempenho.setBackground(new java.awt.Color(228, 87, 12));
        lblRAMDesempenho.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblRAMDesempenho.setForeground(new java.awt.Color(228, 87, 12));
        lblRAMDesempenho.setText("10%");

        jLabel13.setBackground(new java.awt.Color(228, 87, 12));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(228, 87, 12));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("RAM");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tempo de atividade:");

        lblTempoAtividade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTempoAtividade.setForeground(new java.awt.Color(255, 255, 255));
        lblTempoAtividade.setText("__:__:__:__");

        lblDiscoRigido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiscoRigido.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscoRigido.setText("___________");

        lblThreands.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThreands.setForeground(new java.awt.Color(255, 255, 255));
        lblThreands.setText("_______");

        lblP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblP.setForeground(new java.awt.Color(255, 255, 255));
        lblP.setText("Processos:");

        lblProcesses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProcesses.setForeground(new java.awt.Color(255, 255, 255));
        lblProcesses.setText("_______");

        prgDisco.setForeground(new java.awt.Color(228, 87, 12));
        prgDisco.setValue(50);

        lblHDOcupado.setBackground(new java.awt.Color(228, 87, 12));
        lblHDOcupado.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblHDOcupado.setForeground(new java.awt.Color(228, 87, 12));
        lblHDOcupado.setText("10%");

        jLabel16.setBackground(new java.awt.Color(228, 87, 12));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(228, 87, 12));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("HD");

        lblT1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblT1.setForeground(new java.awt.Color(255, 255, 255));
        lblT1.setText("Threands:");

        lblDiscoStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiscoStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscoStatus.setText("___________");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDisco)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiscoTipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lblRAMTotal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRAMUtilizavel)
                                .addGap(14, 14, 14)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRAMDisponivel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRAMTipo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRAMClock))
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblCPUName))))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSistema))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSistemBit)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prgDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTempoAtividade))
                                    .addComponent(lblDiscoRigido))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblT1)
                                .addGap(18, 18, 18)
                                .addComponent(lblThreands)
                                .addGap(34, 34, 34)
                                .addComponent(lblP)
                                .addGap(18, 18, 18)
                                .addComponent(lblProcesses))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCPUDesempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRAMDesempenho)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHDOcupado)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblDiscoStatus))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSistema)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblSistemBit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPUName)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblRAMTotal))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblRAMUtilizavel)
                            .addComponent(jLabel11)
                            .addComponent(lblRAMDisponivel))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRAMTipo)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblRAMClock))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisco)
                            .addComponent(lblDiscoTipo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblTempoAtividade))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPUDesempenho)
                            .addComponent(lblRAMDesempenho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblHDOcupado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblT1)
                    .addComponent(lblThreands)
                    .addComponent(lblP)
                    .addComponent(lblProcesses))
                .addGap(35, 35, 35)
                .addComponent(lblDiscoRigido)
                .addGap(18, 18, 18)
                .addComponent(prgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiscoStatus)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taskun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taskun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taskun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taskun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taskun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCPUDesempenho;
    private javax.swing.JLabel lblCPUName;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblDiscoRigido;
    private javax.swing.JLabel lblDiscoStatus;
    private javax.swing.JLabel lblDiscoTipo;
    private javax.swing.JLabel lblHDOcupado;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblProcesses;
    private javax.swing.JLabel lblRAMClock;
    private javax.swing.JLabel lblRAMDesempenho;
    private javax.swing.JLabel lblRAMDisponivel;
    private javax.swing.JLabel lblRAMTipo;
    private javax.swing.JLabel lblRAMTotal;
    private javax.swing.JLabel lblRAMUtilizavel;
    private javax.swing.JLabel lblSistemBit;
    private javax.swing.JLabel lblSistema;
    private javax.swing.JLabel lblT1;
    private javax.swing.JLabel lblTempoAtividade;
    private javax.swing.JLabel lblThreands;
    private javax.swing.JProgressBar prgDisco;
    // End of variables declaration//GEN-END:variables
}
