/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.oshente;

import java.awt.AWTException;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import oshi.SystemInfo;
import oshi.hardware.CentralProcessor;
import oshi.hardware.GlobalMemory;
import oshi.hardware.HardwareAbstractionLayer;


/**
 *
 * @author pedro
 */
public class Desempenho extends javax.swing.JFrame {
    
    
    
    SystemInfo si = new SystemInfo();
    HardwareAbstractionLayer hal = si.getHardware();
    GlobalMemory ram = hal.getMemory();
    CentralProcessor cpu = hal.getProcessor();
    /**
     * Creates new form Desempenho
     */
    public Desempenho() {
        initComponents();
        
        //String mensagem;
        //mensagem = "Programa 1" + "\n" + "iniciando...";
        //JOptionPane.showMessageDialog (null, mensagem);
       
        //mensagem = "<html><u>Linha 1</u>" + "<br/>" + "<i>Linha 2</i></html>";
       // JOptionPane.showMessageDialog (null, mensagem);
       
     
        
        Double ramDesempenho =(double)(ram.getTotal() - ram.getAvailable());
       

        
//        Timer timer = new Timer(1500, new ActionListener() { 
//        public void actionPerformed(ActionEvent e) {
//            System.out.println("Hello World");
//        }
//        }); 
//        timer.setRepeats (true);     
//        timer.start ();

    ActionListener action;
        action = (ActionEvent actionEvent)->{
            System.out.println("Processando...");
            
           
            
            lblRAMDesem.setText(String.format("%.0f%%",(ramDesempenho * 100.0) / ram.getTotal()));
            
            
        };
    Timer timer = new Timer(1000, action);
    timer.start ();




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCPUDesem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRAMDesem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnMenErro = new javax.swing.JButton();
        btnMenAlert = new javax.swing.JButton();
        btnMenMen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnNotAlert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CPU Desempenho:");

        lblCPUDesem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCPUDesem.setText("__________");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("RAM Desempenho:");

        lblRAMDesem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRAMDesem.setText("__________");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Mensagem");

        btnMenErro.setText("Erro");
        btnMenErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenErroActionPerformed(evt);
            }
        });

        btnMenAlert.setText("Alerta");
        btnMenAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenAlertActionPerformed(evt);
            }
        });

        btnMenMen.setText("Mensagem");
        btnMenMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenMenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnMenErro)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenAlert)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenMen)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenErro)
                    .addComponent(btnMenAlert)
                    .addComponent(btnMenMen))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Notificação");

        btnNotAlert.setText("Alerta");
        btnNotAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotAlertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnNotAlert)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotAlert)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblRAMDesem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCPUDesem))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCPUDesem))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblRAMDesem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenErroActionPerformed
        JOptionPane.showMessageDialog(null, "Ocorreu um erro", "Erro", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnMenErroActionPerformed

    private void btnNotAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotAlertActionPerformed
        Image image = Toolkit.getDefaultToolkit().getImage("");
        TrayIcon trayIcon = new TrayIcon(image);
        
        if (SystemTray.isSupported()) {
            SystemTray tray = SystemTray.getSystemTray();
            
            try {
                tray.add(trayIcon);
                trayIcon.displayMessage("Alerta Notificação", "Você foi notificado", TrayIcon.MessageType.WARNING);
            }
            catch (AWTException e) {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_btnNotAlertActionPerformed

    private void btnMenAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenAlertActionPerformed
       JOptionPane.showMessageDialog(null, "Você foi avisado", "Aviso", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnMenAlertActionPerformed

    private void btnMenMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenMenActionPerformed
        ImageIcon icon = new ImageIcon("C:\\Users\\pedro\\OneDrive - Digital School - BandTec\\1git\\study\\bootstrap\\img\\cat-eye.png");
        JOptionPane.showMessageDialog(null, "Olá tudo bem?", "Mensagem", JOptionPane.PLAIN_MESSAGE, icon);
    }//GEN-LAST:event_btnMenMenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desempenho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desempenho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenAlert;
    private javax.swing.JButton btnMenErro;
    private javax.swing.JButton btnMenMen;
    private javax.swing.JButton btnNotAlert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCPUDesem;
    private javax.swing.JLabel lblRAMDesem;
    // End of variables declaration//GEN-END:variables
}
